/**
 * @defgroup lnp Lyubashevsky-Nguyen-Plancon proof machinery.
 */
/**
 * @file
 *
 * Interface of the LNP-style proof machinery needed by the is_bin sub-proof
 * of Protocol 1 in ePrint 2025/658. See ISBIN-PLAN.md for what this is for
 * and LNP-PARAMS.md for which parts are and are not established.
 *
 * @ingroup lnp
 */

#ifndef LNP_H
#define LNP_H

#include <flint/flint.h>
#include <flint/nmod_poly.h>

#include "param.h"
#include "commit.h"

/*============================================================================*/
/* Constant definitions                                                       */
/*============================================================================*/

/* Number of message slots in the multi-slot commitment. The is_bin proof uses
 * four: the witness, the constant-coefficient mask, and two garbage terms. */
#define SLOTS 	4

/*============================================================================*/
/* Type definitions                                                           */
/*============================================================================*/

/* A commitment key with SLOTS message rows instead of the single row that
 * commit.h provides. The Ajtai part B1 is shared. */
typedef struct _lnpkey_t {
	pcrt_poly_t B1[HEIGHT][WIDTH];
	pcrt_poly_t b2[SLOTS][WIDTH];
} lnpkey_t;

/* A commitment to SLOTS messages under one randomness vector. */
typedef struct _lnpcom_t {
	pcrt_poly_t c1[HEIGHT];
	pcrt_poly_t c2[SLOTS];
} lnpcom_t;

/*============================================================================*/
/* Function prototypes                                                        */
/*============================================================================*/

/**
 * Apply the automorphism sigma_k : X -> X^k to a polynomial given in
 * coefficient representation. This is the reference implementation that the
 * CRT-aware one below is tested against.
 *
 * @param[out] c			- the result, may alias a.
 * @param[in] a				- the polynomial to map.
 * @param[in] k				- the exponent, which must be odd.
 */
void lnp_auto(nmod_poly_t c, const nmod_poly_t a, slong k);

/**
 * Apply the automorphism sigma_k to a polynomial in CRT representation.
 *
 * sigma_k maps the ideal generated by one irreducible factor onto the ideal
 * generated by the other when k = 3 mod 4, and onto itself when k = 1 mod 4,
 * so this is not a componentwise operation.
 *
 * @param[out] c			- the result, may alias a.
 * @param[in] a				- the polynomial in CRT representation.
 * @param[in] k				- the exponent, which must be odd.
 */
void lnp_auto_crt(pcrt_poly_t c, pcrt_poly_t a, slong k);

/**
 * Return whether sigma_k exchanges the two CRT components.
 *
 * @param[in] k				- the exponent, which must be odd.
 * @return 1 if the components are exchanged, 0 if they are fixed.
 */
int lnp_auto_swaps(slong k);

#endif /* LNP_H */
