name: build and test

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libflint-dev libgmp-dev

      - name: Build
        run: make

      - name: Run tests
        run: make test
