name: build and test

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup FLINT
        uses: ./.github/actions/setup-flint
        with:
          version: v3.6.0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgmp-dev

      - name: Build
        run: make

      - name: Run tests
        run: make test

  sanitizers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup FLINT
        uses: ./.github/actions/setup-flint
        with:
          version: v3.6.0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgmp-dev
      - name: Run tests under AddressSanitizer and UndefinedBehaviorSanitizer
        run: |
          make CFLAGS="-O1 -g -march=native -pthread -DTESTS=5 \
            -fsanitize=address,undefined -fno-sanitize-recover=all" test
